<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<ul>
	<li>日常管理
		<ul>
			<li>寝室物品配置</li>
			<li>携物外出登记</li>
			<li>查询信息</li>
		</ul>
	</li>
	<li>人员管理
		<ul>
			<li>管理人员信息</li>
			<li>学生信息</li>
		</ul>
	</li>
	<li>系统管理
		<ul>
			<li>添加用户</li>
			<li>修改用户密码</li>
			<li>退出系统?</li>
		</ul>
	</li>
	<li>帮助信息</li>
</ul>